## 邮件模板配置
spring:
  mail:
    protocol: smtp
    host: smtp.qq.com
    # 自己的qq邮箱账号
    username: 372787553@qq.com
    #  password 换成腾讯给的QQ授权码
    password:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  thymeleaf:
    enabled: true
    mode: LEGACYHTML5
    encoding: UTF-8
    prefix: classpath:/templates/ # 模板存放在资源目录的 templates/ 文件下
    suffix: .html # 模板后缀
    check-template-location: true
    check-template: false
    cache: false # 调试时关闭缓存
    servlet:
      content-type: text/html