server:
  port: 9006

spring:
  application:
    name: github-oauth
  main:
    allow-bean-definition-overriding: true
  mvc:
    #解决restful 404错误 spring.mvc.throw-exception-if-no-handler-found=true spring.resources.add-mappings=false
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: false
    mode: html
    servlet:
      content-type: text/html