server:
  port: 9009

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    #    password:
    timeout: 6000
    # 链接池
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 0
