# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    mode: always
  h2:
    console:
      enabled: true
      settings:
        # 开启h2 console 跟踪 方便调试  默认 false
        trace: true
        # 允许console 远程访问 默认false
        web-allow-others: true
      path: /h2-console
# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**.xml