server:
  port: 9008

spring:
  application:
    name: jdbc-template
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/boke?serverTimezone=CTT&characterEncoding=utf8&autoReconnect=true&useUnicode=true&useSSL=true
    username: root
    password: root
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: DemoHikari
      max-lifetime: 60000
      connection-timeout: 60000
      validation-timeout: 5000
      read-only: false
      login-timeout: 5